# Generated by Django 3.0.5 on 2020-04-24 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='editor',
            field=models.CharField(choices=[('geoq', 'geoq'), ('osm', 'osm'), ('exploiter', 'exploiter'), ('ols', 'ols')], default=('geoq', 'geoq'), help_text='Editor to be used for creating features', max_length=20),
        ),
    ]
