version: '3'

services:
  db:
    image: mdillon/postgis
    environment:
      POSTGRES_PASSWORD: geoq
      POSTGRES_USER: geoq
      POSTGRES_DB: geoq

  web:
    image: centos7
    build: .
    environment:
      ALLOWED_HOST: 'geoq-testing'
    volumes:
      - /home/drocca/actions-runner/_work/geoq/geoq/geoq:/usr/src/geoq
    ports:
      - "8000:8000"
    command: sh -c 'python app.py'
    depends_on:
      - db
